# SPDX-FileCopyrightText: 2026 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure music-assistant paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  with_items:
    - "{{ music_assistant_base_path }}"
    - "{{ music_assistant_data_path }}"

- name: Ensure music-assistant support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ music_assistant_base_path }}/{{ item }}"
    mode: "0640"
  with_items:
    - env
    - labels

- name: Ensure music-assistant container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ music_assistant_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ music_assistant_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else music_assistant_container_image_force_pull }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure music-assistant container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ music_assistant_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure music-assistant systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/music-assistant.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ music_assistant_identifier }}.service"
    mode: "0644"
