# SPDX-FileCopyrightText: 2026 Oliver Lorenz
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of music-assistant systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ music_assistant_identifier }}.service"
  register: music_assistant_service_stat

- name: Uninstall music-assistant systemd services and files
  when: music_assistant_service_stat.stat.exists | bool
  block:
    - name: Ensure music-assistant systemd service is stopped
      ansible.builtin.service:
        name: "{{ music_assistant_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure music-assistant systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ music_assistant_identifier }}.service"
        state: absent

    - name: Ensure music-assistant path does not exist
      ansible.builtin.file:
        path: "{{ music_assistant_base_path }}"
        state: absent
