---
galaxy_info:
  author: Oliver Lorenz
  role_name: ffc_hello
  namespace: oliverlorenz
  description: hello-world nginx served over the Freifunk Chemnitz mesh (ffc-mesh-client sidecar)
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: EL
      versions:
        - all
  license: AGPL-3.0-or-later
  min_ansible_version: "2.1"
